### ISSUE TITLE
Only make sounds on input

### ISSUE THREAD

**Issue by dvcrn** [surdu/typewriter-sounds#1]
Amazing plugin :smile: 

I think it would be a bit better if the sound only happens when you actually input stuff rather than command / ctrl / meta keys. That usually ends up in having 2 sounds at the same time for making brackets. 

Just my 2 cents!

**Comment by surdu** [comment]
Thanks :grin:

I had this in mind, but if you think about it, the backspace and space keys on the typewriter also makes the clank sound although it makes no visible output. 

You can think of it like this: your keyboard is a typewriter, it will clank whatever you press.

Maybe I'll make it as an option, though I think I'll keep it as simple as possible :yum:

I'll leave this open for now, until I give it a deeper thought :wink:

**Comment by akirashimosoeda** [comment]
Also, it will be great if you put the carriage return sound when you type Enter for newline.

**Comment by surdu** [comment]
I'll close this for now. I'm still on the same opinion that:

> the backspace and space keys on the typewriter also makes the clank sound although it makes no visible output

Judging by the lack of thumbs up or other input on this I'll assume not many want this feature.

If there are more people that desire this kind of behaviour or someone creates a pull request for it, I'll be glad to help.
