### ISSUE TITLE
Several new-line sounds overlapping.

### ISSUE THREAD

**Issue by JonShard** [surdu/typewriter-sounds#2]
Love this plug-in. Really fun.
There is only one thing i find a bit annoying. 

When pressing enter several times to make space for a function, create a class or something similar, the new line sound overlaps and gets a bit loud as a result. It would be amazing if that sound in specific only played once, and only restarted after it was done. Hope this is useful :)

**Comment by surdu** [comment]
Glad you like it 😃 

I think what would make more sense here would be to cancel the previous sound before playing a new one. I'll look into it.

Thanks for the feedback 😉

**Comment by JonShard** [comment]
Yes, I agree. That would sounds like it would be better.
